version: '3.8'

services:
  # Основной сервис
  taco-cloud:
    build: ./main-service
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_MAIL_USERNAME: "sabitovratmir05@gmail.com"
      SPRING_MAIL_PASSWORD: "ltom nuzc ozbx vufp"
      DATASOURCE_URL: "jdbc:postgresql://postgres:5432/tacocloud"
      DATASOURCE_USERNAME: "tacocloud"
      DATASOURCE_PASSWORD: "password"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      JWK_SET_URI: "http://auth-service:9000/oauth2/jwks"
      SPRING_JPA_DDL_AUTO: "update"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  # Сервис кухни
  taco-kitchen:
    build: ./kitchen-service
    ports:
      - "9090:9090"
    environment:
      SERVER_PORT: 9090
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_CONSUMER_GROUP_ID: "taco-kitchen-group"
    depends_on:
      kafka:
        condition: service_started

  # Сервис заказов
  order-service:
    build: ./order-service
    ports:
      - "9091:9091"
    environment:
      SERVER_PORT: 9091
      DATASOURCE_URL: "jdbc:postgresql://postgres:5432/tacocloud"
      DATASOURCE_USERNAME: "tacocloud"
      DATASOURCE_PASSWORD: "password"
    depends_on:
      postgres:
        condition: service_healthy

  # Сервис аутентификации (добавлен)
  auth-service:
    build: ./auth-service  # предполагается, что у вас есть этот сервис
    ports:
      - "9000:9000"
    environment:
      SERVER_PORT: 9000
      DATASOURCE_URL: "jdbc:postgresql://postgres:5432/tacocloud"
      DATASOURCE_USERNAME: "tacocloud"
      DATASOURCE_PASSWORD: "password"
    depends_on:
      postgres:
        condition: service_healthy

  # База данных PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: "tacocloud"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "tacocloud"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tacocloud"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Kafka
  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: