taco:
  order:
    pageSize: 15
logging:
  file.name: logs/TacoCloud.log
  file.max-size: 10MB
  level: # indicates the type of log info that is shown
    root: info
    org.springframework.security: debug
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sabitovratmir05@gmail.com  # Ваш Gmail
    password: pgbm unas ymbo zsvo  # Пароль приложений (не основной!)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true  # Шифрование
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  data:
    rest:
      base-path: /data-api

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
    bootstrap-servers: localhost:9092

  datasource:
    generate-unique-name: false
    name: tacocloud

  application:
    name: taco-cloud