taco:
  order:
    pageSize: ${TACO_ORDER_PAGE_SIZE:15}  # Размер страницы (можно переопределить)

logging:
  file:
    name: ${LOGGING_FILE_NAME:logs/TacoCloud.log}  # Путь к логам
    max-size: ${LOGGING_FILE_MAX_SIZE:10MB}         # Макс. размер файла
  level:
    root: ${LOGGING_LEVEL_ROOT:info}                # Уровень логирования
    org.springframework.security: ${LOGGING_LEVEL_SECURITY:debug}

spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}       # SMTP-сервер
    port: ${SPRING_MAIL_PORT:587}                  # Порт
    username: ${SPRING_MAIL_USERNAME:}             # Email (обязательно указать!)
    password: ${SPRING_MAIL_PASSWORD:}             # Пароль (обязательно!)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:}             # URL для JWT (обязательно!)

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/tacocloud}  # URL БД
    username: ${DATASOURCE_USERNAME:tacocloud}      # Логин БД
    password: ${DATASOURCE_PASSWORD:}               # Пароль БД (обязательно!)
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}  # Адрес Kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}      # Стратегия DDL (update/validate)
    show-sql: ${SPRING_JPA_SHOW_SQL:true}          # Показывать SQL в логах?
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:always}         # Инициализация БД (always/never)

  data:
    rest:
      base-path: /data-api                          # Базовый путь API

  application:
    name: taco-cloud                               # Имя приложения

management:
  endpoints:
    web:
      exposure:
        include: '*'                               # Открыть все эндпоинты
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

info:
  contact:
    email: tacoadmin@tacocloud.com                 # Публичный email
    phone: 01-8000-451854                         # Публичный телефон
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"