taco:
  order:
    pageSize: 15
logging:
  file.name: logs/TacoCloud.log
  file.max-size: 10MB
  level: # indicates the type of log info that is shown
    root: info
    org.springframework.security: debug
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sabitovratmir05@gmail.com  # Ваш Gmail
    password: ltom nuzc ozbx vufp  # Пароль приложений (не основной!)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true  # Шифрование
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  data:
    rest:
      base-path: /data-api

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5433/tacocloud
    username: tacocloud
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Автоматическое обновление схемы
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always # Запускать data.sql и schema.sql
  application:
    name: taco-cloud
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
info:
  contact:
    email: tacoadmin@tacocloud.com
    phone: 01-8000-451854
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"